---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog-agent
  namespace: default
spec:
  chart:
    spec:
      chart: datadog
      sourceRef:
        kind: HelmRepository
        name: datadog
        namespace: flux-system
  interval: 1h
  releaseName: datadog-agent-via-flux
  values:
    targetSystem: 'linux'
    datadog:
      apiKey: 4d8afdb4fdf50af62df4bb3e94242a44
      containerCollectAll: false
      logs:
        enabled: true
        autoMultiLineDetection: true
      apm:
        enabled: true
        portEnabled: true
      clusterAgent:
        replicas: 2
        createPodDisruptionBudget: true
        admissionController:
          enabled: true
          mutateUnlabelled: true
      dogstatsd:
        useSocketVolume: true
        useHostPort: true
        nonLocalTraffic: true
      confd:
        redisdb.yaml: |-
          init_config:
          instances:
            - host: bitnami-redis-master.persistent-state.svc.cluster.local
              port: 6379
              password: iU4jrjAFHd4T
    apm_config:
      ## @param ignore_resources - list of strings - optional
      ## A list of regular expressions can be provided to exclude certain traces based on their resource name.
      ## All entries must be surrounded by double quotes and separated by commas.
      ignore_resources: ['(GET|POST) /health']
